# Generated by Django 3.0.8 on 2020-08-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(default='N/A', max_length=64),
        ),
    ]
