# Generated by Django 3.0.8 on 2020-08-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200818_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='amount_of_bids',
            new_name='listing_number',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
