# Generated by Django 3.0.8 on 2020-08-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200820_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
