# Generated by Django 3.0.8 on 2020-08-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_delete_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_number', models.IntegerField()),
                ('user', models.IntegerField()),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
