# Generated by Django 3.0.8 on 2020-08-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
