# Generated by Django 3.0.8 on 2020-08-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
