# Generated by Django 3.0.8 on 2020-08-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200826_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
