# Generated by Django 3.0.8 on 2020-09-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200902_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='user',
        ),
        migrations.AddField(
            model_name='bids',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
