# Generated by Django 3.0.8 on 2020-09-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200902_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='auction',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
