# Generated by Django 3.0.8 on 2020-09-09 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200903_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listing_number',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='listing_number',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='listing_number',
        ),
        migrations.AddField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='b_listing', to='auctions.Auction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_listing', to='auctions.Auction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='w_listing', to='auctions.Auction'),
            preserve_default=False,
        ),
    ]
