# Generated by Django 3.0.8 on 2020-09-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200910_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, default='No category listed', max_length=64),
        ),
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
