# Generated by Django 3.0.8 on 2020-09-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20200910_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(default='No category listed', max_length=64),
        ),
    ]
