# Generated by Django 3.0.8 on 2020-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20200914_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
